name: imaxt
channels:
  - defaults
dependencies:
  - aiohttp
  - alabaster
  - asn1crypto
  - astroid
  - astropy
  - async-timeout
  - atomicwrites
  - attrs
  - autopep8
  - babel
  - backcall
  - blas
  - bokeh
  - ca-certificates
  - certifi
  - cffi
  - chardet
  - click
  - cloudpickle
  - coverage
  - cryptography
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - decorator
  - distributed
  - docutils
  - flake8
  - freetype
  - heapdict
  - idna
  - imageio
  - imagesize
  - intel-openmp
  - ipython
  - ipython_genutils
  - isort
  - jedi
  - jinja2
  - jpeg
  - kiwisolver
  - krb5
  - lazy-object-proxy
  - libedit
  - libffi
  - libgfortran
  - libpng
  - libpq
  - libsodium
  - libtiff
  - locket
  - lz4
  - lz4-c
  - markupsafe
  - matplotlib
  - mccabe
  - mkl
  - mkl_fft
  - mkl_random
  - more-itertools
  - msgpack-python
  - multidict
  - mypy
  - mypy_extensions
  - ncurses
  - networkx
  - numpy
  - numpy-base
  - olefile
  - openssl
  - packaging
  - pandas
  - parso
  - partd
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pluggy
  - prompt_toolkit
  - psutil
  - psycopg2
  - ptyprocess
  - py
  - pycodestyle
  - pycparser
  - pyflakes
  - pygments
  - pylint
  - pyopenssl
  - pyparsing
  - pysocks
  - pytest
  - pytest-arraydiff
  - pytest-astropy
  - pytest-cov
  - pytest-doctestplus
  - pytest-openfiles
  - pytest-remotedata
  - python
  - python-dateutil
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - readline
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - setuptools
  - six
  - snowballstemmer
  - sortedcontainers
  - sphinx
  - sphinxcontrib
  - sphinxcontrib-websupport
  - sqlalchemy
  - sqlite
  - tblib
  - tk
  - toolz
  - tornado
  - traitlets
  - transaction
  - typed-ast
  - urllib3
  - wcwidth
  - wheel
  - wrapt
  - xarray
  - xz
  - yaml
  - yarl
  - zeromq
  - zict
  - zlib
  - zope
  - zope.interface
  - pip:
    - better-exceptions
    - bumpversion
    - dask-image
    - docker
    - docker-pycreds
    - msgpack
    - pims
    - slicerator
    - sphinx-autodoc-typehints
    - voluptuous
    - websocket-client
